import Link from "next/link";
import { Logo } from "@/components/Logo";

const features = [
  ["◎", "Smart Profile", "Turn your resume into a searchable student profile."],
  ["⌕", "AI Connections", "Describe who you need and discover relevant people."],
  ["◫", "Community Feed", "Share ideas, progress, and opportunities with MU."],
  ["↗", "Business Spotlight", "Give your venture a dedicated place to be discovered."],
];

export default function HomePage() {
  return <main className="bg-app text-ink">
    <section className="grid-texture relative min-h-screen overflow-hidden border-b border-line">
      <div className="absolute left-1/2 top-10 h-72 w-72 -translate-x-1/2 rounded-full bg-teal/10 blur-[120px]" />
      <nav className="relative mx-auto flex max-w-6xl items-center justify-between px-6 py-7 lg:px-8"><Logo /><div className="hidden items-center gap-8 text-sm text-muted md:flex"><a href="#how" className="hover:text-ink">How it works</a><a href="#features" className="hover:text-ink">Features</a></div><Link href="/login" className="primary-button !min-h-10 !px-5 !py-2">Join UniConnect</Link></nav>
      <div className="relative mx-auto flex max-w-5xl flex-col items-center px-6 pb-24 pt-24 text-center sm:pt-32"><span className="rounded-full border border-line bg-white/[0.03] px-4 py-2 text-xs font-semibold uppercase tracking-[0.18em] text-muted">Verified Masters&apos; Union students only</span><h1 className="mt-8 max-w-4xl text-5xl font-semibold leading-[0.96] tracking-[-0.06em] sm:text-7xl lg:text-8xl">The people you need are <span className="gradient-text">already here.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-muted">Discover classmates by skills, experience, and what they&apos;re building—then turn a campus full of talent into your strongest network.</p><Link href="/login" className="primary-button mt-10">Sign in with your MU email <span className="ml-2">→</span></Link>
        <div className="panel mt-20 w-full max-w-4xl p-5 text-left shadow-card sm:p-8"><div className="flex items-center gap-2 border-b border-line pb-5"><span className="size-2.5 rounded-full bg-teal" /><span className="size-2.5 rounded-full bg-amber" /><span className="ml-3 text-xs text-muted">Find connections</span></div><div className="mt-6 rounded-xl border border-line bg-app p-5 text-sm text-muted">Find someone who has worked in ecommerce and wants to build a consumer brand.</div><div className="mt-5 grid gap-3 sm:grid-cols-3">{["Growth & ecommerce", "Brand strategy", "Consumer insights"].map((label) => <div className="rounded-xl border border-line bg-elevated p-4" key={label}><div className="size-10 rounded-full bg-gradient-to-br from-teal/60 to-amber/30" /><div className="mt-4 h-2 w-24 rounded bg-white/70" /><p className="mt-3 text-xs text-muted">{label}</p></div>)}</div></div>
      </div>
    </section>
    <section className="mx-auto grid max-w-6xl gap-12 px-6 py-28 lg:grid-cols-2 lg:px-8"><div><p className="eyebrow">The problem</p><h2 className="mt-5 text-4xl font-semibold tracking-[-0.045em] sm:text-5xl">A world-class network shouldn&apos;t depend on chance.</h2></div><p className="self-end text-lg leading-8 text-muted">Across 15+ cohorts and thousands of students, the right collaborator, operator, designer, or founder may be one classroom away—yet discovery is scattered across chats, events, and social profiles.</p></section>
    <section id="how" className="border-y border-line bg-[#0d0d0d]"><div className="mx-auto max-w-6xl px-6 py-28 lg:px-8"><p className="eyebrow">How it works</p><h2 className="mt-5 text-4xl font-semibold tracking-[-0.045em]">From resume to relevant connection.</h2><div className="mt-12 grid gap-px overflow-hidden rounded-2xl border border-line bg-line sm:grid-cols-2 lg:grid-cols-4">{["Verify your MU email", "Upload your resume", "Review your smart profile", "Search and connect"].map((label, index) => <div className="bg-surface p-6" key={label}><span className="gradient-text text-sm font-bold">0{index + 1}</span><p className="mt-12 font-semibold">{label}</p></div>)}</div></div></section>
    <section id="features" className="mx-auto max-w-6xl px-6 py-28 lg:px-8"><p className="eyebrow">Core features</p><div className="mt-5 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><h2 className="max-w-2xl text-4xl font-semibold tracking-[-0.045em]">Built around how ambitious students actually work.</h2><p className="max-w-sm text-sm leading-6 text-muted">One verified space to be known for your skills and discover what others bring.</p></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{features.map(([icon, title, description]) => <article className="panel p-6" key={title}><div className="grid size-11 place-items-center rounded-xl bg-gradient-to-br from-teal to-amber text-xl font-bold text-app">{icon}</div><h3 className="mt-8 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted">{description}</p></article>)}</div></section>
    <section className="border-y border-line bg-[#0d0d0d]"><div className="mx-auto max-w-6xl px-6 py-28 lg:px-8"><p className="eyebrow">Community in action</p><h2 className="mt-5 text-4xl font-semibold tracking-[-0.045em]">People, projects, momentum.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{["Looking for a product designer for a climate-tech sprint.", "Building a D2C nutrition brand and seeking packaging feedback.", "Hosting a small fintech research jam this Friday."].map((copy, index) => <article className="panel p-6" key={copy}><div className="flex items-center gap-3"><div className="size-10 rounded-full bg-gradient-to-br from-teal/70 to-amber/60" /><div><div className="h-2 w-24 rounded bg-white/70" /><p className="mt-2 text-xs text-muted">MU Cohort {2026 - index}</p></div></div><p className="mt-7 leading-7 text-white/80">{copy}</p></article>)}</div></div></section>
    <section className="grid-texture"><div className="mx-auto max-w-4xl px-6 py-28 text-center"><p className="eyebrow">Your network is waiting</p><h2 className="mt-5 text-5xl font-semibold tracking-[-0.05em]">Be discoverable for what you do best.</h2><Link href="/login" className="primary-button mt-9">Join with your MU email</Link><p className="mt-6 text-sm text-muted">Private. Verified. Built for Masters&apos; Union.</p></div><footer className="border-t border-line px-6 py-7"><div className="mx-auto flex max-w-6xl flex-col gap-4 text-sm text-muted sm:flex-row sm:items-center sm:justify-between"><Logo /><p>© 2026 UniConnect · Verified MU students only</p></div></footer></section>
  </main>;
}
