import type { Metadata } from "next";
import Link from "next/link";
import { requireCompleteUser } from "@/lib/auth";
import { getProfileByUserId } from "@/lib/profile-store";

export const metadata: Metadata = { title: "Dashboard" };
export default async function DashboardPage() {
  const user = await requireCompleteUser();
  const profile = await getProfileByUserId(user.id);
  return <main className="min-h-screen px-6 pb-28 pt-10 sm:px-10 lg:px-12"><div className="mx-auto max-w-6xl">{profile?.origin === "masters_cv" && !profile.preloadedNoticeAcknowledgedAt && <section className="mb-8 rounded-2xl border border-teal/35 bg-gradient-to-r from-teal/10 to-amber/10 p-6" role="status"><p className="eyebrow">Profile ready for review</p><h2 className="mt-3 text-xl font-semibold">Your profile was prepared from the Masters&apos; CV we already had.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-white/75">Please check the details and change anything you want. You can also add a photo or upload a newer resume.</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/profile/setup?edit=1" className="primary-button">Review and edit</Link><form action="/api/profile/acknowledge-import" method="post"><button type="submit" className="secondary-button">Got it</button></form></div></section>}<p className="eyebrow">Dashboard</p><div className="mt-4 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-4xl font-semibold tracking-[-0.045em] sm:text-5xl">Welcome back, {profile?.name.split(" ")[0]}.</h1><p className="mt-3 text-muted">Your MU network is ready when you are.</p></div><Link href="/profile" className="secondary-button">View profile</Link></div><div className="mt-10 grid gap-5 md:grid-cols-3"><DashboardCard number={profile?.skills.length ?? 0} label="Skills on your profile" action="Keep your strengths current" href="/profile/setup?edit=1" /><DashboardCard number="AI" label="Connection search" action="Find the right collaborator" href="/connections" /><DashboardCard number="MU" label="Community feed" action="See what people are building" href="/feed" /></div><section className="panel mt-8 p-7 sm:p-9"><p className="eyebrow">Suggested next step</p><h2 className="mt-4 text-2xl font-semibold">Tell the network what you&apos;re building.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-muted">Your current project and collaboration interests help search surface you to the right people.</p><Link href="/profile/setup?edit=1" className="primary-button mt-7">Update profile</Link></section></div></main>;
}
function DashboardCard({ number, label, action, href }: { number: number | string; label: string; action: string; href: string }) { return <Link href={href} className="panel block p-6 transition hover:-translate-y-1 hover:border-white/20"><span className="gradient-text text-3xl font-bold">{number}</span><h2 className="mt-8 font-semibold">{label}</h2><p className="mt-2 text-sm text-muted">{action} →</p></Link>; }
