import Link from "next/link";
import Image from "next/image";
import { notFound } from "next/navigation";
import { requireCompleteUser } from "@/lib/auth";
import { getProfileByUserId } from "@/lib/profile-store";

export default async function ProfilePage() {
  const user = await requireCompleteUser(); const profile = await getProfileByUserId(user.id); if (!profile) notFound();
  return <main className="min-h-screen px-6 pb-28 pt-10 sm:px-10 lg:px-12"><div className="mx-auto max-w-5xl"><div className="flex items-center justify-between"><div><p className="eyebrow">My profile</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.045em]">How MU sees you.</h1></div><Link href="/profile/setup?edit=1" className="secondary-button">Edit profile</Link></div><section className="panel mt-10 p-7 sm:p-10"><div className="flex flex-col gap-7 sm:flex-row sm:items-center">{profile.profilePhotoUrl ? <Image src={profile.profilePhotoUrl} alt={profile.name} width={112} height={112} unoptimized className="size-28 rounded-3xl border border-line object-cover" /> : <div className="grid size-28 place-items-center rounded-3xl bg-gradient-to-br from-teal to-amber text-3xl font-black text-app" aria-label={`${profile.name} profile placeholder`}>{profile.name.slice(0, 1).toUpperCase()}</div>}<div><span className="rounded-full border border-teal/30 bg-teal/10 px-3 py-1 text-xs text-teal">{profile.cohort}</span><h2 className="mt-4 text-3xl font-semibold">{profile.name}</h2><p className="mt-2 text-muted">Looking for {profile.lookingFor}</p></div></div><div className="mt-8 flex flex-wrap gap-2">{profile.skills.map((skill) => <span key={skill} className="rounded-full border border-line bg-white/5 px-3 py-1.5 text-xs text-white/80">{skill}</span>)}</div>{profile.interests.length > 0 && <div className="mt-6"><p className="eyebrow">Into</p><div className="mt-3 flex flex-wrap gap-2">{profile.interests.map((interest) => <span key={interest} className="rounded-full border border-amber/30 bg-amber/5 px-3 py-1.5 text-xs text-amber">{interest}</span>)}</div></div>}{profile.currentProject && <div className="mt-9 border-t border-line pt-7"><p className="eyebrow">Currently building</p><p className="mt-3 max-w-3xl leading-7 text-white/80">{profile.currentProject}</p></div>}</section><div className="mt-6 grid gap-6 md:grid-cols-2"><DetailCard title="Experience">{profile.workExperience.length ? profile.workExperience.map((item) => <div className="border-b border-line py-4 last:border-0" key={`${item.company}-${item.role}`}><p className="font-semibold">{item.role}</p><p className="mt-1 text-sm text-muted">{item.company} · {item.duration}</p><p className="mt-2 text-sm leading-6 text-white/70">{item.description}</p></div>) : <p className="text-sm text-muted">No experience added yet.</p>}</DetailCard><DetailCard title="Education">{profile.education.length ? profile.education.map((item) => <div className="border-b border-line py-4 last:border-0" key={`${item.institution}-${item.degree}`}><p className="font-semibold">{item.degree}</p><p className="mt-1 text-sm text-muted">{item.institution} · {item.year}</p></div>) : <p className="text-sm text-muted">No education added yet.</p>}</DetailCard></div></div></main>;
}
function DetailCard({ title, children }: { title: string; children: React.ReactNode }) { return <section className="panel p-6"><h2 className="text-lg font-semibold">{title}</h2><div className="mt-3">{children}</div></section>; }
